[package]
name = "mole"
version = "0.1.0"
authors = ["Jesse van Rhijn <jesse.v.rhijn@gmail.com>"]

[dependencies]
rand = "0.5.0"
ndarray = "0.12.0"
ndarray-linalg = { version = "0.10.0", features = ["intel-mkl"] }
ndarray-rand = "0.8.0"
